mariadb:
  image: mariadb
  environment:
  - MYSQL_DATABASE=${DBNAME}
  - MYSQL_USER=${DBUSER}
  - MYSQL_PASSWORD=${DBPASS}
  - MYSQL_ROOT_PASSWORD=${ROOTPASS}
racktables:
  build: .
  links:
  - mariadb
    environment:
    - DBHOST=${DBHOST}
    - DBNAME=${DBNAME}
    - DBUSER=${DBUSER}
    - DBPASS=${DBPASS}
nginx:
  image: nginx:stable-alpine
  links:
  - racktables
  volumes_from:
  - racktables
  volumes:
  - ./nginx.conf:/etc/nginx/nginx.conf
  ports:
  - 8000:80